title: Your Site Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Your site description here
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zicoabhidey.github.io/test123/" # your site's URL

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections for CMS
collections:
  pages:
    output: true
    permalink: /:name/

include: ["admin"]

# Exclude files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .bundle/
  - admin/config.yml